site_name: annotations - handle annotation terms and modifiers

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.snippets

nav:
  - introduction.md
  - reference.md
